theme: jekyll-theme-cayman
title: "The Mathematics of Multi-Agent Systems"
description: "MIT HSSP 2022"
name: "MIT HSSP 2022: The Mathematics of Multi-Agent Systems"
github:
  is_project_page: false
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 